### PR TITLE
windows / ST3 compat

### PR DESCRIPTION
**Pull request by selfsame**
Notes:
- using `.sublime-settings` instead of the `config.json`
- passing a port setting to the node process (`.sock` args weren't supported in windows)

### CODE REVIEW

**Comment by shaunlebron** [comment]
thanks for putting this together!  I don't have a windows machine to test this on, but I think @oakmac will look at this soon

**Comment by oakmac** [comment]
I will. Sorry for delayed response on this.

**Comment by JoakimLofgren** [comment]
I played around with the native python parinfer version here:
https://github.com/JoakimLofgren/sublime-text-parinfer/tree/windows-fixes

Although I forgot to look at the PRs before starting :)

**Comment by oakmac** [comment]
@selfsame and @JoakimLofgren - thank you both for your contributions here!

I went ahead and pulled in @JoakimLofgren changes into the master branch.

**Comment by selfsame** [comment]
Ah nice, good work y'all!

**Pull request closed without merging**
